### ISSUE TITLE
Missing licence file

### ISSUE THREAD

**Issue by trouyer** [PaulNieuwelaar/processjs#1]
Hi,

on codeplex (https://processjs.codeplex.com) your code was on CDDL licence. Licence file is missing on this repo. Is your code free/open source or licence has been changed ? Could you add licence file ?

**Comment by PaulNieuwelaar** [comment]
Hi, the license is the same as codeplex, I still need to copy the file across. However it's all open source and free to use as long as you maintain the (C) references etc, and don't resell/repackage the solution as your own IP. Other than that you're free to use it in whatever solutions you need to 🙂

**Comment by trouyer** [comment]
Hi,
thanks for this quick response. I made a pull request to add the license file.
