### ISSUE TITLE
Output Parameters always return null value

### ISSUE THREAD

**Issue by fmarto** [PaulNieuwelaar/processjs#3]
Greetings.
I'm using Dynamics 365 Online v.9.0.
- process Action with input and output parameters.
- Workflow (CodeActivity)
- JavaScript using last version of process.js inside a HTML Web Resource

Obviously the call to my custom Action works properly because I can see the results done by the Activity code. However, the output parameters (params of Success function) always return a null value.

I checked multiple times if all my parameters were defined identically in the JavaScript, the Action, and the C# code. All parameters are "required".

I don't understand why. Please help.

Thanks

-Frank

**Comment by PaulNieuwelaar** [comment]
Hi Frank, are you using an Assign Value step at the end of your Action to set the output parameters? Also are you able to post your code snippet where you're calling the action? Cheers, Paul

**Comment by fvakiliev** [comment]
Hi Paul!
I have similar issue. Success callback function not raised after call action with output parameter (integer).
D365 on-premises 8.2, processjs 2.0.2.0
Regards,
OldCat

**Comment by PaulNieuwelaar** [comment]
Hi, please check the Action is returning the correct values when calling it via a C# console app etc. Most likely it's an issue with the Action itself, e.g. if the Assign Value step isn't being used to set the Output Param on the action, or if you're setting the Output Param in a plugin then the plugin needs to be registered post-op and synchronous.

**Comment by fvakiliev** [comment]
My problem solved! My mistake.
