### ISSUE TITLE
Question - Typescript file?

### ISSUE THREAD

**Issue by eleung83** [PaulNieuwelaar/processjs#4]
As mentioned in the title, this isn't an issue but a question. I'm in the process of converting our JS related to CRM to Typescript, and make use of your Process JS file. 

Although it wouldn't be too difficult to generate a TS file for your JS file, is there any chance that you already have a ts definition file?

**Comment by PaulNieuwelaar** [comment]
Hi, unfortunately I don't. Although if you end up generating one I'd be happy to include it in the project.

**Comment by eleung83** [comment]
Ok, I will try and generate one
