### ISSUE TITLE
Impersonation 

### ISSUE THREAD

**Issue by AntoineGauthier** [PaulNieuwelaar/processjs#5]
Hi,
Thanks for the great work, I've been using that solution for quite some time now and I find it truly helpful!

Although the solution handles most of my needs in 99% of my use cases scenarios, I was wondering if you knew of anyway of calling an action from JavaScript while impersonating the user?  

I don't mind if that solution is a bit more rough or even if it doesn't fit with the solution you currently provide.

Any leads would be greatly appreciated.

Thanks again.

**Comment by PaulNieuwelaar** [comment]
Hi, thanks for the positive feedback :)

What is your action doing that requires impersonation? If your action is calling a plugin, you might be able to do the impersonation inside the plugin. I would often run actions and plugins under the system context to avoid permission errors, then just set the owner etc to the "user" as needed.

Regards,
Paul
