### ISSUE TITLE
Action Calling Custom Code - Object Reference

### ISSUE THREAD

**Issue by MCas86** [PaulNieuwelaar/processjs#6]
I've got an action with 3 parameters:

- InputParameter1 - string - required
- InputParameter2 - string - required
- OutputParameter1 - string - optional

Using Process.callAction, I pass the actionName and 2 input parameters per documentation. It calls the action and runs through the custom code just fine (walked through it multiple times without an issue) and then it still directs to the errorHandler and throws an object reference error. 

Is this caused by not using the output parameter?

**Comment by PaulNieuwelaar** [comment]
Are you capturing the second parameter in the error callback? That should give you the stack trace if it's an error in your plugin. It should only hit the error callback if the action throws an error. Using the output Params is optional. Let me know how you get on. Paul

**Comment by MCas86** [comment]
[Microsoft.Crm.ObjectModel: Microsoft.Crm.ObjectModel.SyncWorkflowExecutionPlugin]
[[someId]: ]
Starting sync workflow '[actionName]', Id: [workflowid]
Entering CustomActivityStep1_step: 
Sync workflow '[actionName]' terminated with error 'Object reference not set to an instance of an object.'

**Comment by PaulNieuwelaar** [comment]
Is your action calling a custom workflow activity? Looks like the error is in that.
